### ISSUE TITLE
Resetting git repo config

### ISSUE THREAD

**Issue by IRTrail** [housam-s/Klipper-Backup#4]
I have, somehow, messed up the git repo config. When I run ./menu.sh, I get "fatal: unable to access 'https://https://github.com/IRTrail/filungar_klipper_backup/': Could not resolve host: https" Obviously, when I pasted in the github repo, I included the "https://" bit when I shouldn't have.

However, I cannot convince it to work correctly. I have tried deleting all associated files. I have also manually ran the git setup commands. All to no avail. That is, of course, if I have ran the git setup commands correctly.

At any rate, is there a way to reset all that so I can re-run ./menu.sh with a clean slate?

Thanks.

**Comment by IRTrail** [comment]
Fixed after no small amount of research:

cd ~/printer_data/config/
git remote set-url origin https://IRTrail:ghp_<token>@github.com/IRTrail/filungar_klipper_backup/

Might I suggest to set up some error checking in the main shell script to catch persons like me who add the "https://" prefix when they shouldn't?

Anyway, thanks for a really nice back up tool!

**Comment by burgoyne-richard** [comment]
Hi @IRTrail,

When you input your git repo the script will now automatically remove the http/https prefix which will resolve the issue you had.

We are looking to overhaul this in the near future to make it more seamless when needing to reset your git config or change repositories.

Thanks for using the script!
